#! /usr/bin/env python
# encoding: utf-8

def build(bld):

  main              = bld.create_obj('cc', 'program')
  main.source       = [
			'manet-visualizer.c',
			'util.c',
			'gl-texture.c',
			'gl-skybox.c',
			'gl-display.c',
			'gl-ground.c',
			'gl-node.c',
			'gl-model-loader.c',
			'gl-terrain.c',
			'event.c',
			'node.c',
			'scenario.c',
			'time.c',
			'trace-parser.c',
			'gl-text.c',
			'trace-parser-ns2.c',
			'packet.c',
			'gl-packet.c',
			]
  main.target       = 'network-visualizer'
  main.includes     = '. /usr/include ../src'
  main.cflags      = '-D_REENTRANT -DDBG_ENABLED -Wall -W -g -O0'
  main.uselib       = 'X11 Xi Xmu glut GL GLU'

